# NextRush Workspace Configuration
# This enables us to have separate packages for benchmarking
# without polluting our main NextRush codebase

packages:
  # Main NextRush framework (zero dependencies)
  - "."

  # Benchmark workspace with all framework dependencies
  - "benchmark/**"

  # Professional benchmarking environment
  - "professional-benchmarks"

  # Future workspaces
  - "examples/**"
  - "plugins/**"
  - "createApp/**"
