packages:
  - packages/*
  - packages/middleware/*
  - packages/extensions/*
  - packages/adapters/*
  - apps/*
  - examples/*

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
