#!/usr/bin/env bash
# init-agent.sh — Scaffold agent-ready files into any web project.
#
# Usage:
#   ./scripts/init-agent.sh                    # prompts for site URL
#   ./scripts/init-agent.sh nextrush.dev       # uses <site> as URL
#   ./scripts/init-agent.sh nextrush.dev ./out # writes to ./out/public/
#
# What it creates (all under <output>/public/):
#   _worker.js                 — Cloudflare Pages worker (MDN + agent endpoints)
#   _headers                   — cache + CORS headers
#   webmcp.js                  — WebMCP tools for in-browser agents
#   .well-known/agent-card.json
#   .well-known/mcp/server-card.json
#   .well-known/agent-skills/index.json
#   .well-known/api-catalog
#
# The worker serves /auth.md and /.well-known/oauth-* at runtime.
# No build step needed — drop into any Pages/Workers project.
set -euo pipefail

SITE="${1:-}"
OUTDIR="${2:-.}"

if [ -z "$SITE" ]; then
  echo "Enter your site domain (e.g., example.com):"
  read -r SITE
  SITE="${SITE%/}"
fi

if [ -z "$SITE" ]; then
  echo "Error: domain required."
  exit 1
fi

PUBDIR="$OUTDIR/public"
mkdir -p "$PUBDIR/.well-known/mcp"
mkdir -p "$PUBDIR/.well-known/agent-skills"

# ──────────────────────────────────────────────
# Helper: write file only if target doesn't exist
# (never overwrite user changes)
# ──────────────────────────────────────────────
write_file() {
  local path="$1"
  if [ -f "$path" ]; then
    echo "  ⏭️  exists: $path"
    return
  fi
  cat > "$path"
  echo "  ✅ created: $path"
}

# ── _worker.js ────────────────────────────────
write_file "$PUBDIR/_worker.js" << WORKEREOF
/**
 * _worker.js — Cloudflare Pages worker.
 * Serves agent-discovery files (auth.md, OAuth metadata) directly,
 * and handles markdown content negotiation (\`Accept: text/markdown\`).
 * Generated by init-agent.sh for ${SITE}
 */

const ROUTE_MAP = [
  { prefix: '/docs/',   replace: '/api/mdx/',    stripIndex: '/docs' },
  { prefix: '/blog/',   replace: '/api/blog/',    stripIndex: '/blog' },
  { prefix: '/skills/', replace: '/api/skills/',  stripIndex: '/skills' },
];

function toMarkdownPath(pathname) {
  const normalized = pathname.endsWith('/') && pathname !== '/'
    ? pathname.slice(0, -1)
    : pathname;
  if (normalized === '/') return '/api/mdx/index.md';
  for (const route of ROUTE_MAP) {
    if (normalized === route.stripIndex) return route.replace + 'index.md';
    if (normalized.startsWith(route.prefix)) {
      const rest = normalized.slice(route.prefix.length);
      if (!rest) return route.replace + 'index.md';
      return route.replace + rest + '.md';
    }
  }
  return null;
}

const MIME_MAP = {
  '.js':   'application/javascript',
  '.mjs':  'application/javascript',
  '.css':  'text/css',
  '.json': 'application/json',
  '.md':   'text/markdown; charset=utf-8',
  '.wasm': 'application/wasm',
  '.svg':  'image/svg+xml',
};

function fixMimeType(response, pathname) {
  for (const [ext, mime] of Object.entries(MIME_MAP)) {
    if (!pathname.endsWith(ext)) continue;
    const ct = response.headers.get('Content-Type') || '';
    if (ct === mime || ct.startsWith(mime + ';')) return response;
    const headers = new Headers(response.headers);
    headers.set('Content-Type', mime);
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  }
  return response;
}

function estimateTokens(text) {
  const words = text.split(/\s+/).filter(Boolean).length;
  return Math.ceil(words * 1.3);
}

const AUTH_MD_CONTENT = \`# auth.md — Agent Registration for ${SITE}

This service supports **agentic registration**: discover → register → access.
Follow the steps in order; do not skip ahead.

## Step 1 — Discover

Fetch the OAuth Protected Resource Metadata:

\`\`\`http
GET /.well-known/oauth-protected-resource HTTP/1.1
Host: ${SITE}
\`\`\`

Response:

\`\`\`json
{
  "resource": "https://${SITE}",
  "authorization_servers": ["https://${SITE}"],
  "scopes_supported": ["read:docs", "read:blog", "read:skills", "read:catalog"],
  "bearer_methods_supported": ["header"],
  "resource_documentation": "https://${SITE}/auth.md"
}
\`\`\`

## Step 2 — Fetch the Authorization Server Metadata

\`\`\`http
GET /.well-known/oauth-authorization-server HTTP/1.1
Host: ${SITE}
\`\`\`

Response uses standard RFC 8414 fields plus the \`agent_auth\` block:

\`\`\`json
{
  "issuer": "https://${SITE}",
  "token_endpoint": "https://${SITE}/auth.md",
  "grant_types_supported": ["urn:ietf:params:oauth:grant-type:jwt-bearer"],
  "scopes_supported": ["read:docs", "read:blog", "read:skills", "read:catalog"],
  "agent_auth": {
    "skill": "https://${SITE}/auth.md",
    "identity_endpoint": "https://${SITE}/auth.md",
    "claim_endpoint": "https://${SITE}/auth.md",
    "events_endpoint": "https://${SITE}/auth.md",
    "identity_types_supported": ["anonymous"],
    "identity_assertion": { "assertion_types_supported": [] },
    "events_supported": []
  }
}
\`\`\`

## Step 3 — Register

This is a public site. No credentials required. All scopes are granted automatically.

\`\`\`json
{
  "registration_id": "reg_anonymous",
  "registration_type": "anonymous",
  "scopes": ["read:docs", "read:blog", "read:skills", "read:catalog"]
}
\`\`\`

## Step 4 — Access Resources

Use \`Accept: text/markdown\` header for markdown responses. No bearer token needed.

## Contact

Documentation: https://${SITE}/docs
\`;

// ── OAuth metadata ───────────────────────────
const OAUTH_METADATA = new Map([
  ['/.well-known/oauth-authorization-server', {
    contentType: 'application/json',
    body: JSON.stringify({
      issuer: 'https://${SITE}',
      authorization_endpoint: 'https://${SITE}/auth.md',
      token_endpoint: 'https://${SITE}/auth.md',
      scopes_supported: ['read:docs', 'read:blog', 'read:skills', 'read:catalog'],
      response_types_supported: [],
      grant_types_supported: ['urn:ietf:params:oauth:grant-type:jwt-bearer'],
      token_endpoint_auth_methods_supported: [],
      service_documentation: 'https://${SITE}/auth.md',
      op_policy_uri: 'https://${SITE}/auth.md',
      op_tos_uri: 'https://${SITE}/docs',
      agent_auth: {
        skill: 'https://${SITE}/auth.md',
        identity_endpoint: 'https://${SITE}/auth.md',
        claim_endpoint: 'https://${SITE}/auth.md',
        events_endpoint: 'https://${SITE}/auth.md',
        identity_types_supported: ['anonymous'],
        identity_assertion: { assertion_types_supported: [] },
        events_supported: [],
      },
    }),
  }],
  ['/.well-known/oauth-protected-resource', {
    contentType: 'application/oauth-protected-resource-v1+json',
    body: JSON.stringify({
      resource: 'https://${SITE}',
      authorization_servers: ['https://${SITE}'],
      scopes_supported: ['read:docs', 'read:blog', 'read:skills', 'read:catalog'],
      bearer_methods_supported: ['header'],
      resource_documentation: 'https://${SITE}/auth.md',
    }),
  }],
]);

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const accept = request.headers.get('Accept') || '';

    // Serve agent endpoints directly (bypass asset cache)
    if (url.pathname === '/auth.md' || url.pathname === '/.well-known/auth.md') {
      return new Response(AUTH_MD_CONTENT, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'Cache-Control': 'no-cache',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    const metadata = OAUTH_METADATA.get(url.pathname);
    if (metadata) {
      return new Response(metadata.body, {
        headers: {
          'Content-Type': metadata.contentType,
          'Cache-Control': 'no-cache',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    // Fast path: skip content negotiation when markdown isn't requested
    if (!accept.includes('text/markdown')) {
      const res = await env.ASSETS.fetch(request);
      return fixMimeType(res, url.pathname);
    }

    const markdownPath = toMarkdownPath(url.pathname);
    if (!markdownPath) {
      const res = await env.ASSETS.fetch(request);
      return fixMimeType(res, url.pathname);
    }

    const mdUrl = new URL(markdownPath, url);
    const mdReq = new Request(mdUrl, request);
    const mdRes = await env.ASSETS.fetch(mdReq);

    if (!mdRes.ok) {
      const res = await env.ASSETS.fetch(request);
      return fixMimeType(res, url.pathname);
    }

    const body = await mdRes.text();
    const tokens = estimateTokens(body);

    return new Response(body, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'x-markdown-tokens': String(tokens),
        'content-signal': 'ai-train=yes, search=yes, ai-input=yes',
        'Vary': 'Accept',
        'Cache-Control': 'public, max-age=3600',
      },
    });
  },
};
WORKEREOF

# ── _headers ─────────────────────────────────
write_file "$PUBDIR/_headers" << HEADERSEOF
# CORS headers for agent discovery files
/.well-known/*
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=3600

/auth.md
  Access-Control-Allow-Origin: *
  Cache-Control: no-cache

# Security headers
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
HEADERSEOF

# ── webmcp.js ────────────────────────────────
write_file "$PUBDIR/webmcp.js" << WEBMCPEOF
// WebMCP — Tool registration for browser-based AI agents.
// Generated by init-agent.sh for ${SITE}
// https://webmcp.org

(function () {
  if (typeof window === 'undefined') return;

  const SITE = '${SITE}';

  const tools = [
    {
      name: 'get_documentation',
      description: \`Fetch documentation content from \${SITE} for a given path (e.g., /docs/routing)\`,
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Documentation path like /docs/routing' },
        },
        required: ['path'],
      },
      handler: async ({ path }) => {
        const res = await fetch(\`https://\${SITE}\${path}\`, {
          headers: { Accept: 'text/markdown' },
        });
        if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);
        return { content: [{ type: 'text', text: await res.text() }] };
      },
    },
    {
      name: 'list_skills',
      description: \`List all available agent skills published by \${SITE}\`,
      inputSchema: { type: 'object', properties: {} },
      handler: async () => {
        const res = await fetch(\`https://\${SITE}/.well-known/agent-skills/index.json\`);
        if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);
        return { content: [{ type: 'text', text: await res.text() }] };
      },
    },
    {
      name: 'get_api_catalog',
      description: \`Get the API catalog listing available APIs (RFC 9727) for \${SITE}\`,
      inputSchema: { type: 'object', properties: {} },
      handler: async () => {
        const res = await fetch(\`https://\${SITE}/.well-known/api-catalog\`);
        if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);
        return { content: [{ type: 'text', text: await res.text() }] };
      },
    },
  ];

  // Register via imperative API (for agent-supporting browsers)
  if (typeof navigator.modelContext?.registerTool === 'function') {
    tools.forEach((t) => navigator.modelContext.registerTool(t));
  }

  // Also expose on window for direct access
  window.__webmcp_tools = tools;
})();
WEBMCPEOF

# ── .well-known/agent-card.json ──────────────
write_file "$PUBDIR/.well-known/agent-card.json" << AGENTCARDEOF
{
  "name": "${SITE} Documentation",
  "version": "1.0.0",
  "description": "Agent-accessible documentation for ${SITE}.",
  "capabilities": {
    "contentNegotiation": { "markdown": true, "format": "text/markdown" },
    "discovery": {
      "agentSkills": true,
      "apiCatalog": true,
      "dnsAid": false
    }
  },
  "skills": [
    {
      "id": "documentation",
      "name": "${SITE} Framework",
      "description": "Provides documentation, skills discovery, and API catalog via agent-friendly endpoints.",
      "url": "https://${SITE}/docs",
      "tools": [
        { "name": "get_documentation", "description": "Fetch documentation for a given path" },
        { "name": "list_skills", "description": "List all published agent skills" },
        { "name": "get_api_catalog", "description": "Get the API catalog" }
      ]
    }
  ]
}
AGENTCARDEOF

# ── .well-known/mcp/server-card.json ─────────
write_file "$PUBDIR/.well-known/mcp/server-card.json" << MCPCARDEOF
{
  "name": "${SITE} Documentation",
  "description": "Documentation, skills, and API catalog for ${SITE}.",
  "version": "1.0.0",
  "capabilities": {
    "tools": {},
    "resources": {
      "listChanged": false,
      "subscribe": false
    }
  }
}
MCPCARDEOF

# ── .well-known/agent-skills/index.json ──────
write_file "$PUBDIR/.well-known/agent-skills/index.json" << SKILLSEOF
{
  "\$schema": "https://raw.githubusercontent.com/cloudflare/agents/main/skills/schema.v0.2.0.json",
  "name": "${SITE} Agent Skills",
  "description": "Agent-accessible skills for the ${SITE} documentation site.",
  "version": "1.0.0",
  "skills": [
    {
      "id": "read-docs",
      "name": "Read Documentation",
      "description": "Read documentation pages from ${SITE}",
      "endpoint": "https://${SITE}/docs",
      "accept": "text/markdown",
      "parameters": {
        "path": {
          "type": "string",
          "description": "Documentation path (e.g., /docs/routing)"
        }
      }
    },
    {
      "id": "list-skills",
      "name": "List Agent Skills",
      "description": "List all available agent skills for ${SITE}",
      "endpoint": "https://${SITE}/.well-known/agent-skills/index.json"
    },
    {
      "id": "list-api-catalog",
      "name": "List API Catalog",
      "description": "List available APIs in the catalog",
      "endpoint": "https://${SITE}/.well-known/api-catalog"
    }
  ]
}
SKILLSEOF

# ── .well-known/api-catalog ─────────────────
write_file "$PUBDIR/.well-known/api-catalog" << APICATALOGEOF
{
  "linkset": [
    {
      "anchor": "https://${SITE}",
      "service-desc": [
        { "href": "https://${SITE}/openapi.json", "type": "application/json" }
      ],
      "service-doc": [
        { "href": "https://${SITE}/docs", "type": "text/html" }
      ],
      "status": [
        { "href": "https://${SITE}/health", "type": "application/json" }
      ]
    }
  ]
}
APICATALOGEOF

# ── Summary ──────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Agent-ready scaffolding complete"
echo "  Site: ${SITE}"
echo "  Path: ${PUBDIR}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Files created:"
find "$PUBDIR" -type f | sort | sed 's/^/  /'
echo ""
echo "Next steps:"
echo "  1. Deploy to Cloudflare Pages: wrangler pages deploy --project-name <name> --directory ${PUBDIR}"
echo "  2. Set DNS to point ${SITE} to Cloudflare"
echo "  3. Verify at https://isitagentready.com"
echo ""
echo "Note: The _worker.js assumes markdown negotiation routes"
echo "for /docs/, /blog/, /skills/ — edit ROUTE_MAP if needed."
