/**
 * @nextrush/dev - Adapter scaffold templates (Adapter Development Kit, group 11).
 *
 * Pure functions producing the files for `nextrush generate adapter <name>` — a
 * contract-conformant starting point wired to the shared conformance suite, so a
 * third-party runtime adapter is *certifiable from day one*. No I/O here.
 *
 * @packageDocumentation
 */

import { toPascalCase } from './templates.js';

/**
 * The adapter source: a working, contract-conformant `createFetchHandler` that
 * delegates to the Web-standard edge engine as a baseline (most new runtimes are
 * fetch-based), plus the compile-time `satisfies`-style `FetchAdapter` guard.
 */
export function adapterSourceTemplate(name: string): string {
  return `/**
 * @nextrush/adapter-${name}
 *
 * Generated by \`nextrush generate adapter ${name}\`. A contract-conformant
 * starting point: it delegates to the Web-standard edge engine, so it works and
 * passes conformance immediately. Replace the delegation below with
 * ${name}-specific request/response handling as you build the adapter out.
 */
import type { Application } from '@nextrush/core';
import type { FetchAdapter } from '@nextrush/types';
import {
  createFetchHandler as createEdgeFetchHandler,
  type EdgeExecutionContext,
} from '@nextrush/adapter-edge';

/** Build a fetch handler for the ${name} runtime. */
export function createFetchHandler(
  app: Application,
  options?: Parameters<typeof createEdgeFetchHandler>[1],
): ReturnType<typeof createEdgeFetchHandler> {
  // TODO(${name}): customize. This delegates to the shared Web-standard engine as
  // a working baseline — swap in ${name}-specific handling (e.g. its native
  // request/response objects, platform context) here.
  return createEdgeFetchHandler(app, options);
}

// Compile-time contract guard: if the exported shape drifts from the shared
// FetchAdapter contract, this stops compiling.
const _conformance: FetchAdapter<Application, EdgeExecutionContext> = { createFetchHandler };
void _conformance;

// TODO(${name}): when you build a CUSTOM Context (not delegating to edge), also
// prove your factory satisfies the shared contract:
//
//   import type { AdapterContextFactory } from '@nextrush/types';
//   const _ctxFactory: AdapterContextFactory<[Request], ${toPascalCase(name)}Context> = create${toPascalCase(name)}Context;
//   void _ctxFactory;
`;
}

/**
 * The conformance test: a {@link ConformanceDriver} for the generated adapter
 * (driving its real `createFetchHandler`) plus the shared suite. Passes out of
 * the box; keeps passing as you customize — or tells you exactly what diverged.
 */
export function adapterConformanceTestTemplate(name: string): string {
  return `/**
 * Conformance for the ${name} adapter — runs the SAME cross-adapter behavioral
 * suite the built-in adapters pass, via the testing-tier entrypoint.
 */
import { describe } from 'vitest';
import { createApp, type Application } from '@nextrush/core';
import {
  defineConformanceSuite,
  type Configure,
  type ConformanceDriver,
  type DispatchInit,
  type DispatchResult,
} from '@nextrush/adapter-conformance';
import { createFetchHandler } from '../adapter';

function buildRequest(init: DispatchInit | undefined, signal?: AbortSignal): Request {
  const requestInit: RequestInit = { method: init?.method ?? 'GET', headers: init?.headers };
  if (init?.body !== undefined) requestInit.body = init.body;
  if (signal) requestInit.signal = signal;
  return new Request(\`http://localhost\${init?.path ?? '/'}\`, requestInit);
}

async function toResult(response: Response): Promise<DispatchResult> {
  const bodyText = await response.text();
  return {
    status: response.status,
    header: (n) => response.headers.get(n) ?? undefined,
    setCookies: () => response.headers.getSetCookie(),
    text: () => bodyText,
  };
}

const ${name.replace(/-/g, '')}Driver: ConformanceDriver = {
  name: '${name}',
  handlerTimeout504: true,        // TODO(${name}): set to your adapter's real timeout model
  teardownOnShutdown: false,      // TODO(${name}): true if your adapter runs extension destroy()
  transportAbortFiresSignal: true,// TODO(${name}): false if your platform buffers the request

  async dispatch(configure: Configure, init?: DispatchInit): Promise<DispatchResult> {
    const app: Application = createApp({ proxy: init?.proxy ?? false });
    configure(app);
    await app.ready();
    return toResult(await createFetchHandler(app)(buildRequest(init)));
  },

  async abortFiresSignal(): Promise<boolean> {
    let fired = false;
    const controller = new AbortController();
    const app = createApp();
    app.use(async (ctx) => {
      await new Promise<void>((resolve) => {
        if (ctx.signal.aborted) { fired = true; resolve(); return; }
        ctx.signal.addEventListener('abort', () => { fired = true; resolve(); }, { once: true });
      });
    });
    await app.ready();
    const pending = Promise.resolve(createFetchHandler(app)(buildRequest({ path: '/' }, controller.signal)));
    setTimeout(() => controller.abort(), 5);
    await pending.catch(() => undefined);
    return fired;
  },

  async timeoutResult(): Promise<{ status: number; signalFired: boolean }> {
    let signalFired = false;
    const app = createApp();
    app.use(async (ctx) => {
      await new Promise<void>((resolve) => {
        ctx.signal.addEventListener('abort', () => { signalFired = true; resolve(); }, { once: true });
      });
    });
    await app.ready();
    const response = await createFetchHandler(app, { timeout: 10 })(buildRequest({ path: '/' }));
    return { status: response.status, signalFired };
  },
};

describe('${name} adapter conformance', () => {
  defineConformanceSuite(${name.replace(/-/g, '')}Driver);
});
`;
}

/** A sample golden fixture the author expands per platform. */
export function adapterFixtureTemplate(): string {
  return `${JSON.stringify(
    {
      name: 'hello',
      request: { method: 'GET', path: '/hello' },
      expected: { status: 200, body: { message: 'hello' } },
    },
    null,
    2,
  )}\n`;
}

/** README explaining how to certify and customize the adapter. */
export function adapterReadmeTemplate(name: string): string {
  return `# @nextrush/adapter-${name}

Scaffolded by \`nextrush generate adapter ${name}\`. A NextRush runtime adapter,
**certifiable from day one** — it ships wired to the shared cross-adapter
conformance suite.

## Certify

\`\`\`bash
pnpm test   # runs the shared conformance suite against this adapter
\`\`\`

The suite (\`@nextrush/adapter-conformance\`) asserts identical observable behavior
to the built-in Node/Bun/Deno/Edge/serverless adapters. The generated adapter
passes out of the box because it delegates to the Web-standard engine; it keeps
passing as you customize — or tells you exactly which behavior diverged.

## Customize

1. Edit \`src/adapter.ts\` — replace the edge delegation in \`createFetchHandler\`
   with ${name}-specific request/response handling. The \`FetchAdapter\` guard keeps
   your public shape honest.
2. If you build a custom \`Context\`, add the \`AdapterContextFactory\` guard shown in
   the TODO in \`src/adapter.ts\`.
3. Set the three capability flags in \`src/__tests__/conformance.test.ts\` to match
   your runtime's real model (timeout, teardown, transport-abort). Legitimate
   differences are *encoded* as flags, never skipped.

## CI

See \`ci-snippet.yml\` — drop it into \`.github/workflows/\` to run the conformance
suite on every push.
`;
}

/** A ready-to-use CI snippet running the conformance suite. */
export function adapterCiSnippetTemplate(name: string): string {
  return `# Drop into .github/workflows/ — certifies the ${name} adapter on every push.
name: ${name} adapter conformance
on: [push, pull_request]
jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @nextrush/adapter-${name} test
`;
}

/** All files the adapter scaffold emits, keyed by path relative to the adapter dir. */
export function adapterFiles(name: string): Record<string, string> {
  return {
    'src/adapter.ts': adapterSourceTemplate(name),
    'src/__tests__/conformance.test.ts': adapterConformanceTestTemplate(name),
    'fixtures/hello.json': adapterFixtureTemplate(),
    'README.md': adapterReadmeTemplate(name),
    'ci-snippet.yml': adapterCiSnippetTemplate(name),
  };
}
